// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/internationalization/pkg/db/ent/applang"
	"github.com/NpoolPlatform/internationalization/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// AppLangUpdate is the builder for updating AppLang entities.
type AppLangUpdate struct {
	config
	hooks    []Hook
	mutation *AppLangMutation
}

// Where appends a list predicates to the AppLangUpdate builder.
func (alu *AppLangUpdate) Where(ps ...predicate.AppLang) *AppLangUpdate {
	alu.mutation.Where(ps...)
	return alu
}

// SetAppID sets the "app_id" field.
func (alu *AppLangUpdate) SetAppID(u uuid.UUID) *AppLangUpdate {
	alu.mutation.SetAppID(u)
	return alu
}

// SetLangID sets the "lang_id" field.
func (alu *AppLangUpdate) SetLangID(u uuid.UUID) *AppLangUpdate {
	alu.mutation.SetLangID(u)
	return alu
}

// SetMainLang sets the "main_lang" field.
func (alu *AppLangUpdate) SetMainLang(b bool) *AppLangUpdate {
	alu.mutation.SetMainLang(b)
	return alu
}

// SetNillableMainLang sets the "main_lang" field if the given value is not nil.
func (alu *AppLangUpdate) SetNillableMainLang(b *bool) *AppLangUpdate {
	if b != nil {
		alu.SetMainLang(*b)
	}
	return alu
}

// SetCreateAt sets the "create_at" field.
func (alu *AppLangUpdate) SetCreateAt(u uint32) *AppLangUpdate {
	alu.mutation.ResetCreateAt()
	alu.mutation.SetCreateAt(u)
	return alu
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (alu *AppLangUpdate) SetNillableCreateAt(u *uint32) *AppLangUpdate {
	if u != nil {
		alu.SetCreateAt(*u)
	}
	return alu
}

// AddCreateAt adds u to the "create_at" field.
func (alu *AppLangUpdate) AddCreateAt(u int32) *AppLangUpdate {
	alu.mutation.AddCreateAt(u)
	return alu
}

// SetUpdateAt sets the "update_at" field.
func (alu *AppLangUpdate) SetUpdateAt(u uint32) *AppLangUpdate {
	alu.mutation.ResetUpdateAt()
	alu.mutation.SetUpdateAt(u)
	return alu
}

// AddUpdateAt adds u to the "update_at" field.
func (alu *AppLangUpdate) AddUpdateAt(u int32) *AppLangUpdate {
	alu.mutation.AddUpdateAt(u)
	return alu
}

// SetDeleteAt sets the "delete_at" field.
func (alu *AppLangUpdate) SetDeleteAt(u uint32) *AppLangUpdate {
	alu.mutation.ResetDeleteAt()
	alu.mutation.SetDeleteAt(u)
	return alu
}

// SetNillableDeleteAt sets the "delete_at" field if the given value is not nil.
func (alu *AppLangUpdate) SetNillableDeleteAt(u *uint32) *AppLangUpdate {
	if u != nil {
		alu.SetDeleteAt(*u)
	}
	return alu
}

// AddDeleteAt adds u to the "delete_at" field.
func (alu *AppLangUpdate) AddDeleteAt(u int32) *AppLangUpdate {
	alu.mutation.AddDeleteAt(u)
	return alu
}

// Mutation returns the AppLangMutation object of the builder.
func (alu *AppLangUpdate) Mutation() *AppLangMutation {
	return alu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (alu *AppLangUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	alu.defaults()
	if len(alu.hooks) == 0 {
		affected, err = alu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AppLangMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			alu.mutation = mutation
			affected, err = alu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(alu.hooks) - 1; i >= 0; i-- {
			if alu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = alu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, alu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (alu *AppLangUpdate) SaveX(ctx context.Context) int {
	affected, err := alu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (alu *AppLangUpdate) Exec(ctx context.Context) error {
	_, err := alu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (alu *AppLangUpdate) ExecX(ctx context.Context) {
	if err := alu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (alu *AppLangUpdate) defaults() {
	if _, ok := alu.mutation.UpdateAt(); !ok {
		v := applang.UpdateDefaultUpdateAt()
		alu.mutation.SetUpdateAt(v)
	}
}

func (alu *AppLangUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   applang.Table,
			Columns: applang.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: applang.FieldID,
			},
		},
	}
	if ps := alu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := alu.mutation.AppID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: applang.FieldAppID,
		})
	}
	if value, ok := alu.mutation.LangID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: applang.FieldLangID,
		})
	}
	if value, ok := alu.mutation.MainLang(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: applang.FieldMainLang,
		})
	}
	if value, ok := alu.mutation.CreateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: applang.FieldCreateAt,
		})
	}
	if value, ok := alu.mutation.AddedCreateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: applang.FieldCreateAt,
		})
	}
	if value, ok := alu.mutation.UpdateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: applang.FieldUpdateAt,
		})
	}
	if value, ok := alu.mutation.AddedUpdateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: applang.FieldUpdateAt,
		})
	}
	if value, ok := alu.mutation.DeleteAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: applang.FieldDeleteAt,
		})
	}
	if value, ok := alu.mutation.AddedDeleteAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: applang.FieldDeleteAt,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, alu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{applang.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// AppLangUpdateOne is the builder for updating a single AppLang entity.
type AppLangUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AppLangMutation
}

// SetAppID sets the "app_id" field.
func (aluo *AppLangUpdateOne) SetAppID(u uuid.UUID) *AppLangUpdateOne {
	aluo.mutation.SetAppID(u)
	return aluo
}

// SetLangID sets the "lang_id" field.
func (aluo *AppLangUpdateOne) SetLangID(u uuid.UUID) *AppLangUpdateOne {
	aluo.mutation.SetLangID(u)
	return aluo
}

// SetMainLang sets the "main_lang" field.
func (aluo *AppLangUpdateOne) SetMainLang(b bool) *AppLangUpdateOne {
	aluo.mutation.SetMainLang(b)
	return aluo
}

// SetNillableMainLang sets the "main_lang" field if the given value is not nil.
func (aluo *AppLangUpdateOne) SetNillableMainLang(b *bool) *AppLangUpdateOne {
	if b != nil {
		aluo.SetMainLang(*b)
	}
	return aluo
}

// SetCreateAt sets the "create_at" field.
func (aluo *AppLangUpdateOne) SetCreateAt(u uint32) *AppLangUpdateOne {
	aluo.mutation.ResetCreateAt()
	aluo.mutation.SetCreateAt(u)
	return aluo
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (aluo *AppLangUpdateOne) SetNillableCreateAt(u *uint32) *AppLangUpdateOne {
	if u != nil {
		aluo.SetCreateAt(*u)
	}
	return aluo
}

// AddCreateAt adds u to the "create_at" field.
func (aluo *AppLangUpdateOne) AddCreateAt(u int32) *AppLangUpdateOne {
	aluo.mutation.AddCreateAt(u)
	return aluo
}

// SetUpdateAt sets the "update_at" field.
func (aluo *AppLangUpdateOne) SetUpdateAt(u uint32) *AppLangUpdateOne {
	aluo.mutation.ResetUpdateAt()
	aluo.mutation.SetUpdateAt(u)
	return aluo
}

// AddUpdateAt adds u to the "update_at" field.
func (aluo *AppLangUpdateOne) AddUpdateAt(u int32) *AppLangUpdateOne {
	aluo.mutation.AddUpdateAt(u)
	return aluo
}

// SetDeleteAt sets the "delete_at" field.
func (aluo *AppLangUpdateOne) SetDeleteAt(u uint32) *AppLangUpdateOne {
	aluo.mutation.ResetDeleteAt()
	aluo.mutation.SetDeleteAt(u)
	return aluo
}

// SetNillableDeleteAt sets the "delete_at" field if the given value is not nil.
func (aluo *AppLangUpdateOne) SetNillableDeleteAt(u *uint32) *AppLangUpdateOne {
	if u != nil {
		aluo.SetDeleteAt(*u)
	}
	return aluo
}

// AddDeleteAt adds u to the "delete_at" field.
func (aluo *AppLangUpdateOne) AddDeleteAt(u int32) *AppLangUpdateOne {
	aluo.mutation.AddDeleteAt(u)
	return aluo
}

// Mutation returns the AppLangMutation object of the builder.
func (aluo *AppLangUpdateOne) Mutation() *AppLangMutation {
	return aluo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (aluo *AppLangUpdateOne) Select(field string, fields ...string) *AppLangUpdateOne {
	aluo.fields = append([]string{field}, fields...)
	return aluo
}

// Save executes the query and returns the updated AppLang entity.
func (aluo *AppLangUpdateOne) Save(ctx context.Context) (*AppLang, error) {
	var (
		err  error
		node *AppLang
	)
	aluo.defaults()
	if len(aluo.hooks) == 0 {
		node, err = aluo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AppLangMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			aluo.mutation = mutation
			node, err = aluo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(aluo.hooks) - 1; i >= 0; i-- {
			if aluo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = aluo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, aluo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (aluo *AppLangUpdateOne) SaveX(ctx context.Context) *AppLang {
	node, err := aluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (aluo *AppLangUpdateOne) Exec(ctx context.Context) error {
	_, err := aluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aluo *AppLangUpdateOne) ExecX(ctx context.Context) {
	if err := aluo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (aluo *AppLangUpdateOne) defaults() {
	if _, ok := aluo.mutation.UpdateAt(); !ok {
		v := applang.UpdateDefaultUpdateAt()
		aluo.mutation.SetUpdateAt(v)
	}
}

func (aluo *AppLangUpdateOne) sqlSave(ctx context.Context) (_node *AppLang, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   applang.Table,
			Columns: applang.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: applang.FieldID,
			},
		},
	}
	id, ok := aluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AppLang.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := aluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, applang.FieldID)
		for _, f := range fields {
			if !applang.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != applang.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := aluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aluo.mutation.AppID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: applang.FieldAppID,
		})
	}
	if value, ok := aluo.mutation.LangID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: applang.FieldLangID,
		})
	}
	if value, ok := aluo.mutation.MainLang(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: applang.FieldMainLang,
		})
	}
	if value, ok := aluo.mutation.CreateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: applang.FieldCreateAt,
		})
	}
	if value, ok := aluo.mutation.AddedCreateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: applang.FieldCreateAt,
		})
	}
	if value, ok := aluo.mutation.UpdateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: applang.FieldUpdateAt,
		})
	}
	if value, ok := aluo.mutation.AddedUpdateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: applang.FieldUpdateAt,
		})
	}
	if value, ok := aluo.mutation.DeleteAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: applang.FieldDeleteAt,
		})
	}
	if value, ok := aluo.mutation.AddedDeleteAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: applang.FieldDeleteAt,
		})
	}
	_node = &AppLang{config: aluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, aluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{applang.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
