// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/internationalization/pkg/db/ent/applang"
	"github.com/NpoolPlatform/internationalization/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// AppLangQuery is the builder for querying AppLang entities.
type AppLangQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.AppLang
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AppLangQuery builder.
func (alq *AppLangQuery) Where(ps ...predicate.AppLang) *AppLangQuery {
	alq.predicates = append(alq.predicates, ps...)
	return alq
}

// Limit adds a limit step to the query.
func (alq *AppLangQuery) Limit(limit int) *AppLangQuery {
	alq.limit = &limit
	return alq
}

// Offset adds an offset step to the query.
func (alq *AppLangQuery) Offset(offset int) *AppLangQuery {
	alq.offset = &offset
	return alq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (alq *AppLangQuery) Unique(unique bool) *AppLangQuery {
	alq.unique = &unique
	return alq
}

// Order adds an order step to the query.
func (alq *AppLangQuery) Order(o ...OrderFunc) *AppLangQuery {
	alq.order = append(alq.order, o...)
	return alq
}

// First returns the first AppLang entity from the query.
// Returns a *NotFoundError when no AppLang was found.
func (alq *AppLangQuery) First(ctx context.Context) (*AppLang, error) {
	nodes, err := alq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{applang.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (alq *AppLangQuery) FirstX(ctx context.Context) *AppLang {
	node, err := alq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AppLang ID from the query.
// Returns a *NotFoundError when no AppLang ID was found.
func (alq *AppLangQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = alq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{applang.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (alq *AppLangQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := alq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AppLang entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AppLang entity is found.
// Returns a *NotFoundError when no AppLang entities are found.
func (alq *AppLangQuery) Only(ctx context.Context) (*AppLang, error) {
	nodes, err := alq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{applang.Label}
	default:
		return nil, &NotSingularError{applang.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (alq *AppLangQuery) OnlyX(ctx context.Context) *AppLang {
	node, err := alq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AppLang ID in the query.
// Returns a *NotSingularError when more than one AppLang ID is found.
// Returns a *NotFoundError when no entities are found.
func (alq *AppLangQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = alq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{applang.Label}
	default:
		err = &NotSingularError{applang.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (alq *AppLangQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := alq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AppLangs.
func (alq *AppLangQuery) All(ctx context.Context) ([]*AppLang, error) {
	if err := alq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return alq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (alq *AppLangQuery) AllX(ctx context.Context) []*AppLang {
	nodes, err := alq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AppLang IDs.
func (alq *AppLangQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := alq.Select(applang.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (alq *AppLangQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := alq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (alq *AppLangQuery) Count(ctx context.Context) (int, error) {
	if err := alq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return alq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (alq *AppLangQuery) CountX(ctx context.Context) int {
	count, err := alq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (alq *AppLangQuery) Exist(ctx context.Context) (bool, error) {
	if err := alq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return alq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (alq *AppLangQuery) ExistX(ctx context.Context) bool {
	exist, err := alq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AppLangQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (alq *AppLangQuery) Clone() *AppLangQuery {
	if alq == nil {
		return nil
	}
	return &AppLangQuery{
		config:     alq.config,
		limit:      alq.limit,
		offset:     alq.offset,
		order:      append([]OrderFunc{}, alq.order...),
		predicates: append([]predicate.AppLang{}, alq.predicates...),
		// clone intermediate query.
		sql:    alq.sql.Clone(),
		path:   alq.path,
		unique: alq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AppID uuid.UUID `json:"app_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AppLang.Query().
//		GroupBy(applang.FieldAppID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (alq *AppLangQuery) GroupBy(field string, fields ...string) *AppLangGroupBy {
	group := &AppLangGroupBy{config: alq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := alq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return alq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AppID uuid.UUID `json:"app_id,omitempty"`
//	}
//
//	client.AppLang.Query().
//		Select(applang.FieldAppID).
//		Scan(ctx, &v)
//
func (alq *AppLangQuery) Select(fields ...string) *AppLangSelect {
	alq.fields = append(alq.fields, fields...)
	return &AppLangSelect{AppLangQuery: alq}
}

func (alq *AppLangQuery) prepareQuery(ctx context.Context) error {
	for _, f := range alq.fields {
		if !applang.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if alq.path != nil {
		prev, err := alq.path(ctx)
		if err != nil {
			return err
		}
		alq.sql = prev
	}
	return nil
}

func (alq *AppLangQuery) sqlAll(ctx context.Context) ([]*AppLang, error) {
	var (
		nodes = []*AppLang{}
		_spec = alq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &AppLang{config: alq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, alq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (alq *AppLangQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := alq.querySpec()
	_spec.Node.Columns = alq.fields
	if len(alq.fields) > 0 {
		_spec.Unique = alq.unique != nil && *alq.unique
	}
	return sqlgraph.CountNodes(ctx, alq.driver, _spec)
}

func (alq *AppLangQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := alq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (alq *AppLangQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   applang.Table,
			Columns: applang.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: applang.FieldID,
			},
		},
		From:   alq.sql,
		Unique: true,
	}
	if unique := alq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := alq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, applang.FieldID)
		for i := range fields {
			if fields[i] != applang.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := alq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := alq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := alq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := alq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (alq *AppLangQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(alq.driver.Dialect())
	t1 := builder.Table(applang.Table)
	columns := alq.fields
	if len(columns) == 0 {
		columns = applang.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if alq.sql != nil {
		selector = alq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if alq.unique != nil && *alq.unique {
		selector.Distinct()
	}
	for _, p := range alq.predicates {
		p(selector)
	}
	for _, p := range alq.order {
		p(selector)
	}
	if offset := alq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := alq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AppLangGroupBy is the group-by builder for AppLang entities.
type AppLangGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (algb *AppLangGroupBy) Aggregate(fns ...AggregateFunc) *AppLangGroupBy {
	algb.fns = append(algb.fns, fns...)
	return algb
}

// Scan applies the group-by query and scans the result into the given value.
func (algb *AppLangGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := algb.path(ctx)
	if err != nil {
		return err
	}
	algb.sql = query
	return algb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (algb *AppLangGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := algb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (algb *AppLangGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(algb.fields) > 1 {
		return nil, errors.New("ent: AppLangGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := algb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (algb *AppLangGroupBy) StringsX(ctx context.Context) []string {
	v, err := algb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (algb *AppLangGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = algb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{applang.Label}
	default:
		err = fmt.Errorf("ent: AppLangGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (algb *AppLangGroupBy) StringX(ctx context.Context) string {
	v, err := algb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (algb *AppLangGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(algb.fields) > 1 {
		return nil, errors.New("ent: AppLangGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := algb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (algb *AppLangGroupBy) IntsX(ctx context.Context) []int {
	v, err := algb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (algb *AppLangGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = algb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{applang.Label}
	default:
		err = fmt.Errorf("ent: AppLangGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (algb *AppLangGroupBy) IntX(ctx context.Context) int {
	v, err := algb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (algb *AppLangGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(algb.fields) > 1 {
		return nil, errors.New("ent: AppLangGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := algb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (algb *AppLangGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := algb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (algb *AppLangGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = algb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{applang.Label}
	default:
		err = fmt.Errorf("ent: AppLangGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (algb *AppLangGroupBy) Float64X(ctx context.Context) float64 {
	v, err := algb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (algb *AppLangGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(algb.fields) > 1 {
		return nil, errors.New("ent: AppLangGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := algb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (algb *AppLangGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := algb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (algb *AppLangGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = algb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{applang.Label}
	default:
		err = fmt.Errorf("ent: AppLangGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (algb *AppLangGroupBy) BoolX(ctx context.Context) bool {
	v, err := algb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (algb *AppLangGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range algb.fields {
		if !applang.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := algb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := algb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (algb *AppLangGroupBy) sqlQuery() *sql.Selector {
	selector := algb.sql.Select()
	aggregation := make([]string, 0, len(algb.fns))
	for _, fn := range algb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(algb.fields)+len(algb.fns))
		for _, f := range algb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(algb.fields...)...)
}

// AppLangSelect is the builder for selecting fields of AppLang entities.
type AppLangSelect struct {
	*AppLangQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (als *AppLangSelect) Scan(ctx context.Context, v interface{}) error {
	if err := als.prepareQuery(ctx); err != nil {
		return err
	}
	als.sql = als.AppLangQuery.sqlQuery(ctx)
	return als.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (als *AppLangSelect) ScanX(ctx context.Context, v interface{}) {
	if err := als.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (als *AppLangSelect) Strings(ctx context.Context) ([]string, error) {
	if len(als.fields) > 1 {
		return nil, errors.New("ent: AppLangSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := als.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (als *AppLangSelect) StringsX(ctx context.Context) []string {
	v, err := als.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (als *AppLangSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = als.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{applang.Label}
	default:
		err = fmt.Errorf("ent: AppLangSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (als *AppLangSelect) StringX(ctx context.Context) string {
	v, err := als.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (als *AppLangSelect) Ints(ctx context.Context) ([]int, error) {
	if len(als.fields) > 1 {
		return nil, errors.New("ent: AppLangSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := als.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (als *AppLangSelect) IntsX(ctx context.Context) []int {
	v, err := als.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (als *AppLangSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = als.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{applang.Label}
	default:
		err = fmt.Errorf("ent: AppLangSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (als *AppLangSelect) IntX(ctx context.Context) int {
	v, err := als.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (als *AppLangSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(als.fields) > 1 {
		return nil, errors.New("ent: AppLangSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := als.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (als *AppLangSelect) Float64sX(ctx context.Context) []float64 {
	v, err := als.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (als *AppLangSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = als.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{applang.Label}
	default:
		err = fmt.Errorf("ent: AppLangSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (als *AppLangSelect) Float64X(ctx context.Context) float64 {
	v, err := als.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (als *AppLangSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(als.fields) > 1 {
		return nil, errors.New("ent: AppLangSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := als.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (als *AppLangSelect) BoolsX(ctx context.Context) []bool {
	v, err := als.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (als *AppLangSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = als.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{applang.Label}
	default:
		err = fmt.Errorf("ent: AppLangSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (als *AppLangSelect) BoolX(ctx context.Context) bool {
	v, err := als.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (als *AppLangSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := als.sql.Query()
	if err := als.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
