// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/internationalization/pkg/db/ent/country"
	"github.com/NpoolPlatform/internationalization/pkg/db/ent/predicate"
)

// CountryUpdate is the builder for updating Country entities.
type CountryUpdate struct {
	config
	hooks    []Hook
	mutation *CountryMutation
}

// Where appends a list predicates to the CountryUpdate builder.
func (cu *CountryUpdate) Where(ps ...predicate.Country) *CountryUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetCountry sets the "country" field.
func (cu *CountryUpdate) SetCountry(s string) *CountryUpdate {
	cu.mutation.SetCountry(s)
	return cu
}

// SetFlag sets the "flag" field.
func (cu *CountryUpdate) SetFlag(s string) *CountryUpdate {
	cu.mutation.SetFlag(s)
	return cu
}

// SetCreateAt sets the "create_at" field.
func (cu *CountryUpdate) SetCreateAt(u uint32) *CountryUpdate {
	cu.mutation.ResetCreateAt()
	cu.mutation.SetCreateAt(u)
	return cu
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (cu *CountryUpdate) SetNillableCreateAt(u *uint32) *CountryUpdate {
	if u != nil {
		cu.SetCreateAt(*u)
	}
	return cu
}

// AddCreateAt adds u to the "create_at" field.
func (cu *CountryUpdate) AddCreateAt(u int32) *CountryUpdate {
	cu.mutation.AddCreateAt(u)
	return cu
}

// SetUpdateAt sets the "update_at" field.
func (cu *CountryUpdate) SetUpdateAt(u uint32) *CountryUpdate {
	cu.mutation.ResetUpdateAt()
	cu.mutation.SetUpdateAt(u)
	return cu
}

// AddUpdateAt adds u to the "update_at" field.
func (cu *CountryUpdate) AddUpdateAt(u int32) *CountryUpdate {
	cu.mutation.AddUpdateAt(u)
	return cu
}

// SetDeleteAt sets the "delete_at" field.
func (cu *CountryUpdate) SetDeleteAt(u uint32) *CountryUpdate {
	cu.mutation.ResetDeleteAt()
	cu.mutation.SetDeleteAt(u)
	return cu
}

// SetNillableDeleteAt sets the "delete_at" field if the given value is not nil.
func (cu *CountryUpdate) SetNillableDeleteAt(u *uint32) *CountryUpdate {
	if u != nil {
		cu.SetDeleteAt(*u)
	}
	return cu
}

// AddDeleteAt adds u to the "delete_at" field.
func (cu *CountryUpdate) AddDeleteAt(u int32) *CountryUpdate {
	cu.mutation.AddDeleteAt(u)
	return cu
}

// Mutation returns the CountryMutation object of the builder.
func (cu *CountryUpdate) Mutation() *CountryMutation {
	return cu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CountryUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	cu.defaults()
	if len(cu.hooks) == 0 {
		affected, err = cu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CountryMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cu.mutation = mutation
			affected, err = cu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cu.hooks) - 1; i >= 0; i-- {
			if cu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CountryUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CountryUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CountryUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cu *CountryUpdate) defaults() {
	if _, ok := cu.mutation.UpdateAt(); !ok {
		v := country.UpdateDefaultUpdateAt()
		cu.mutation.SetUpdateAt(v)
	}
}

func (cu *CountryUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   country.Table,
			Columns: country.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: country.FieldID,
			},
		},
	}
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Country(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: country.FieldCountry,
		})
	}
	if value, ok := cu.mutation.Flag(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: country.FieldFlag,
		})
	}
	if value, ok := cu.mutation.CreateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: country.FieldCreateAt,
		})
	}
	if value, ok := cu.mutation.AddedCreateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: country.FieldCreateAt,
		})
	}
	if value, ok := cu.mutation.UpdateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: country.FieldUpdateAt,
		})
	}
	if value, ok := cu.mutation.AddedUpdateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: country.FieldUpdateAt,
		})
	}
	if value, ok := cu.mutation.DeleteAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: country.FieldDeleteAt,
		})
	}
	if value, ok := cu.mutation.AddedDeleteAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: country.FieldDeleteAt,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{country.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// CountryUpdateOne is the builder for updating a single Country entity.
type CountryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CountryMutation
}

// SetCountry sets the "country" field.
func (cuo *CountryUpdateOne) SetCountry(s string) *CountryUpdateOne {
	cuo.mutation.SetCountry(s)
	return cuo
}

// SetFlag sets the "flag" field.
func (cuo *CountryUpdateOne) SetFlag(s string) *CountryUpdateOne {
	cuo.mutation.SetFlag(s)
	return cuo
}

// SetCreateAt sets the "create_at" field.
func (cuo *CountryUpdateOne) SetCreateAt(u uint32) *CountryUpdateOne {
	cuo.mutation.ResetCreateAt()
	cuo.mutation.SetCreateAt(u)
	return cuo
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (cuo *CountryUpdateOne) SetNillableCreateAt(u *uint32) *CountryUpdateOne {
	if u != nil {
		cuo.SetCreateAt(*u)
	}
	return cuo
}

// AddCreateAt adds u to the "create_at" field.
func (cuo *CountryUpdateOne) AddCreateAt(u int32) *CountryUpdateOne {
	cuo.mutation.AddCreateAt(u)
	return cuo
}

// SetUpdateAt sets the "update_at" field.
func (cuo *CountryUpdateOne) SetUpdateAt(u uint32) *CountryUpdateOne {
	cuo.mutation.ResetUpdateAt()
	cuo.mutation.SetUpdateAt(u)
	return cuo
}

// AddUpdateAt adds u to the "update_at" field.
func (cuo *CountryUpdateOne) AddUpdateAt(u int32) *CountryUpdateOne {
	cuo.mutation.AddUpdateAt(u)
	return cuo
}

// SetDeleteAt sets the "delete_at" field.
func (cuo *CountryUpdateOne) SetDeleteAt(u uint32) *CountryUpdateOne {
	cuo.mutation.ResetDeleteAt()
	cuo.mutation.SetDeleteAt(u)
	return cuo
}

// SetNillableDeleteAt sets the "delete_at" field if the given value is not nil.
func (cuo *CountryUpdateOne) SetNillableDeleteAt(u *uint32) *CountryUpdateOne {
	if u != nil {
		cuo.SetDeleteAt(*u)
	}
	return cuo
}

// AddDeleteAt adds u to the "delete_at" field.
func (cuo *CountryUpdateOne) AddDeleteAt(u int32) *CountryUpdateOne {
	cuo.mutation.AddDeleteAt(u)
	return cuo
}

// Mutation returns the CountryMutation object of the builder.
func (cuo *CountryUpdateOne) Mutation() *CountryMutation {
	return cuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CountryUpdateOne) Select(field string, fields ...string) *CountryUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Country entity.
func (cuo *CountryUpdateOne) Save(ctx context.Context) (*Country, error) {
	var (
		err  error
		node *Country
	)
	cuo.defaults()
	if len(cuo.hooks) == 0 {
		node, err = cuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CountryMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cuo.mutation = mutation
			node, err = cuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cuo.hooks) - 1; i >= 0; i-- {
			if cuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CountryUpdateOne) SaveX(ctx context.Context) *Country {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CountryUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CountryUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cuo *CountryUpdateOne) defaults() {
	if _, ok := cuo.mutation.UpdateAt(); !ok {
		v := country.UpdateDefaultUpdateAt()
		cuo.mutation.SetUpdateAt(v)
	}
}

func (cuo *CountryUpdateOne) sqlSave(ctx context.Context) (_node *Country, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   country.Table,
			Columns: country.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: country.FieldID,
			},
		},
	}
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Country.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, country.FieldID)
		for _, f := range fields {
			if !country.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != country.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Country(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: country.FieldCountry,
		})
	}
	if value, ok := cuo.mutation.Flag(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: country.FieldFlag,
		})
	}
	if value, ok := cuo.mutation.CreateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: country.FieldCreateAt,
		})
	}
	if value, ok := cuo.mutation.AddedCreateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: country.FieldCreateAt,
		})
	}
	if value, ok := cuo.mutation.UpdateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: country.FieldUpdateAt,
		})
	}
	if value, ok := cuo.mutation.AddedUpdateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: country.FieldUpdateAt,
		})
	}
	if value, ok := cuo.mutation.DeleteAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: country.FieldDeleteAt,
		})
	}
	if value, ok := cuo.mutation.AddedDeleteAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: country.FieldDeleteAt,
		})
	}
	_node = &Country{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{country.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
