// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/internationalization/pkg/db/ent/message"
	"github.com/NpoolPlatform/internationalization/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// MessageUpdate is the builder for updating Message entities.
type MessageUpdate struct {
	config
	hooks    []Hook
	mutation *MessageMutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (mu *MessageUpdate) Where(ps ...predicate.Message) *MessageUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetAppID sets the "app_id" field.
func (mu *MessageUpdate) SetAppID(u uuid.UUID) *MessageUpdate {
	mu.mutation.SetAppID(u)
	return mu
}

// SetMessageID sets the "message_id" field.
func (mu *MessageUpdate) SetMessageID(u uuid.UUID) *MessageUpdate {
	mu.mutation.SetMessageID(u)
	return mu
}

// SetLang sets the "lang" field.
func (mu *MessageUpdate) SetLang(s string) *MessageUpdate {
	mu.mutation.SetLang(s)
	return mu
}

// SetMessage sets the "message" field.
func (mu *MessageUpdate) SetMessage(s string) *MessageUpdate {
	mu.mutation.SetMessage(s)
	return mu
}

// SetCreateAt sets the "create_at" field.
func (mu *MessageUpdate) SetCreateAt(u uint32) *MessageUpdate {
	mu.mutation.ResetCreateAt()
	mu.mutation.SetCreateAt(u)
	return mu
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableCreateAt(u *uint32) *MessageUpdate {
	if u != nil {
		mu.SetCreateAt(*u)
	}
	return mu
}

// AddCreateAt adds u to the "create_at" field.
func (mu *MessageUpdate) AddCreateAt(u uint32) *MessageUpdate {
	mu.mutation.AddCreateAt(u)
	return mu
}

// SetUpdateAt sets the "update_at" field.
func (mu *MessageUpdate) SetUpdateAt(u uint32) *MessageUpdate {
	mu.mutation.ResetUpdateAt()
	mu.mutation.SetUpdateAt(u)
	return mu
}

// AddUpdateAt adds u to the "update_at" field.
func (mu *MessageUpdate) AddUpdateAt(u uint32) *MessageUpdate {
	mu.mutation.AddUpdateAt(u)
	return mu
}

// SetDeleteAt sets the "delete_at" field.
func (mu *MessageUpdate) SetDeleteAt(u uint32) *MessageUpdate {
	mu.mutation.ResetDeleteAt()
	mu.mutation.SetDeleteAt(u)
	return mu
}

// SetNillableDeleteAt sets the "delete_at" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableDeleteAt(u *uint32) *MessageUpdate {
	if u != nil {
		mu.SetDeleteAt(*u)
	}
	return mu
}

// AddDeleteAt adds u to the "delete_at" field.
func (mu *MessageUpdate) AddDeleteAt(u uint32) *MessageUpdate {
	mu.mutation.AddDeleteAt(u)
	return mu
}

// Mutation returns the MessageMutation object of the builder.
func (mu *MessageUpdate) Mutation() *MessageMutation {
	return mu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MessageUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	mu.defaults()
	if len(mu.hooks) == 0 {
		affected, err = mu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MessageMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mu.mutation = mutation
			affected, err = mu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mu.hooks) - 1; i >= 0; i-- {
			if mu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MessageUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MessageUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MessageUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mu *MessageUpdate) defaults() {
	if _, ok := mu.mutation.UpdateAt(); !ok {
		v := message.UpdateDefaultUpdateAt()
		mu.mutation.SetUpdateAt(v)
	}
}

func (mu *MessageUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   message.Table,
			Columns: message.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: message.FieldID,
			},
		},
	}
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.AppID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: message.FieldAppID,
		})
	}
	if value, ok := mu.mutation.MessageID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: message.FieldMessageID,
		})
	}
	if value, ok := mu.mutation.Lang(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: message.FieldLang,
		})
	}
	if value, ok := mu.mutation.Message(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: message.FieldMessage,
		})
	}
	if value, ok := mu.mutation.CreateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: message.FieldCreateAt,
		})
	}
	if value, ok := mu.mutation.AddedCreateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: message.FieldCreateAt,
		})
	}
	if value, ok := mu.mutation.UpdateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: message.FieldUpdateAt,
		})
	}
	if value, ok := mu.mutation.AddedUpdateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: message.FieldUpdateAt,
		})
	}
	if value, ok := mu.mutation.DeleteAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: message.FieldDeleteAt,
		})
	}
	if value, ok := mu.mutation.AddedDeleteAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: message.FieldDeleteAt,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// MessageUpdateOne is the builder for updating a single Message entity.
type MessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageMutation
}

// SetAppID sets the "app_id" field.
func (muo *MessageUpdateOne) SetAppID(u uuid.UUID) *MessageUpdateOne {
	muo.mutation.SetAppID(u)
	return muo
}

// SetMessageID sets the "message_id" field.
func (muo *MessageUpdateOne) SetMessageID(u uuid.UUID) *MessageUpdateOne {
	muo.mutation.SetMessageID(u)
	return muo
}

// SetLang sets the "lang" field.
func (muo *MessageUpdateOne) SetLang(s string) *MessageUpdateOne {
	muo.mutation.SetLang(s)
	return muo
}

// SetMessage sets the "message" field.
func (muo *MessageUpdateOne) SetMessage(s string) *MessageUpdateOne {
	muo.mutation.SetMessage(s)
	return muo
}

// SetCreateAt sets the "create_at" field.
func (muo *MessageUpdateOne) SetCreateAt(u uint32) *MessageUpdateOne {
	muo.mutation.ResetCreateAt()
	muo.mutation.SetCreateAt(u)
	return muo
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableCreateAt(u *uint32) *MessageUpdateOne {
	if u != nil {
		muo.SetCreateAt(*u)
	}
	return muo
}

// AddCreateAt adds u to the "create_at" field.
func (muo *MessageUpdateOne) AddCreateAt(u uint32) *MessageUpdateOne {
	muo.mutation.AddCreateAt(u)
	return muo
}

// SetUpdateAt sets the "update_at" field.
func (muo *MessageUpdateOne) SetUpdateAt(u uint32) *MessageUpdateOne {
	muo.mutation.ResetUpdateAt()
	muo.mutation.SetUpdateAt(u)
	return muo
}

// AddUpdateAt adds u to the "update_at" field.
func (muo *MessageUpdateOne) AddUpdateAt(u uint32) *MessageUpdateOne {
	muo.mutation.AddUpdateAt(u)
	return muo
}

// SetDeleteAt sets the "delete_at" field.
func (muo *MessageUpdateOne) SetDeleteAt(u uint32) *MessageUpdateOne {
	muo.mutation.ResetDeleteAt()
	muo.mutation.SetDeleteAt(u)
	return muo
}

// SetNillableDeleteAt sets the "delete_at" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableDeleteAt(u *uint32) *MessageUpdateOne {
	if u != nil {
		muo.SetDeleteAt(*u)
	}
	return muo
}

// AddDeleteAt adds u to the "delete_at" field.
func (muo *MessageUpdateOne) AddDeleteAt(u uint32) *MessageUpdateOne {
	muo.mutation.AddDeleteAt(u)
	return muo
}

// Mutation returns the MessageMutation object of the builder.
func (muo *MessageUpdateOne) Mutation() *MessageMutation {
	return muo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MessageUpdateOne) Select(field string, fields ...string) *MessageUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Message entity.
func (muo *MessageUpdateOne) Save(ctx context.Context) (*Message, error) {
	var (
		err  error
		node *Message
	)
	muo.defaults()
	if len(muo.hooks) == 0 {
		node, err = muo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MessageMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			muo.mutation = mutation
			node, err = muo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(muo.hooks) - 1; i >= 0; i-- {
			if muo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = muo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, muo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MessageUpdateOne) SaveX(ctx context.Context) *Message {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MessageUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MessageUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (muo *MessageUpdateOne) defaults() {
	if _, ok := muo.mutation.UpdateAt(); !ok {
		v := message.UpdateDefaultUpdateAt()
		muo.mutation.SetUpdateAt(v)
	}
}

func (muo *MessageUpdateOne) sqlSave(ctx context.Context) (_node *Message, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   message.Table,
			Columns: message.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: message.FieldID,
			},
		},
	}
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Message.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, message.FieldID)
		for _, f := range fields {
			if !message.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != message.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.AppID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: message.FieldAppID,
		})
	}
	if value, ok := muo.mutation.MessageID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: message.FieldMessageID,
		})
	}
	if value, ok := muo.mutation.Lang(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: message.FieldLang,
		})
	}
	if value, ok := muo.mutation.Message(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: message.FieldMessage,
		})
	}
	if value, ok := muo.mutation.CreateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: message.FieldCreateAt,
		})
	}
	if value, ok := muo.mutation.AddedCreateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: message.FieldCreateAt,
		})
	}
	if value, ok := muo.mutation.UpdateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: message.FieldUpdateAt,
		})
	}
	if value, ok := muo.mutation.AddedUpdateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: message.FieldUpdateAt,
		})
	}
	if value, ok := muo.mutation.DeleteAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: message.FieldDeleteAt,
		})
	}
	if value, ok := muo.mutation.AddedDeleteAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: message.FieldDeleteAt,
		})
	}
	_node = &Message{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
