// Code generated by entc, DO NOT EDIT.

package message

import (
	"fmt"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the message type in the database.
	Label = "message"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAppID holds the string denoting the app_id field in the database.
	FieldAppID = "app_id"
	// FieldMessageID holds the string denoting the message_id field in the database.
	FieldMessageID = "message_id"
	// FieldLang holds the string denoting the lang field in the database.
	FieldLang = "lang"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// FieldCreateAt holds the string denoting the create_at field in the database.
	FieldCreateAt = "create_at"
	// FieldUpdateAt holds the string denoting the update_at field in the database.
	FieldUpdateAt = "update_at"
	// FieldDeleteAt holds the string denoting the delete_at field in the database.
	FieldDeleteAt = "delete_at"
	// Table holds the table name of the message in the database.
	Table = "messages"
)

// Columns holds all SQL columns for message fields.
var Columns = []string{
	FieldID,
	FieldAppID,
	FieldMessageID,
	FieldLang,
	FieldMessage,
	FieldCreateAt,
	FieldUpdateAt,
	FieldDeleteAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateAt holds the default value on creation for the "create_at" field.
	DefaultCreateAt func() uint32
	// DefaultUpdateAt holds the default value on creation for the "update_at" field.
	DefaultUpdateAt func() uint32
	// UpdateDefaultUpdateAt holds the default value on update for the "update_at" field.
	UpdateDefaultUpdateAt func() uint32
	// DefaultDeleteAt holds the default value on creation for the "delete_at" field.
	DefaultDeleteAt func() uint32
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Lang defines the type for the "lang" enum field.
type Lang string

// Lang values.
const (
	LangZhCN Lang = "zh_CN"
	LangEnUS Lang = "en_US"
)

func (l Lang) String() string {
	return string(l)
}

// LangValidator is a validator for the "lang" field enum values. It is called by the builders before save.
func LangValidator(l Lang) error {
	switch l {
	case LangZhCN, LangEnUS:
		return nil
	default:
		return fmt.Errorf("message: invalid enum value for lang field: %q", l)
	}
}
