FROM jrei/systemd-centos:7

COPY Internationalization.viper.yaml /etc/Internationalization/Internationalization.viper.yaml
COPY internationalization /usr/local/bin/internationalization

CMD ["internationalization", "run"]
