// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package npool

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InternationalizationClient is the client API for Internationalization service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternationalizationClient interface {
	// Method Version
	Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type internationalizationClient struct {
	cc grpc.ClientConnInterface
}

func NewInternationalizationClient(cc grpc.ClientConnInterface) InternationalizationClient {
	return &internationalizationClient{cc}
}

func (c *internationalizationClient) Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/internationalization.v1.Internationalization/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternationalizationServer is the server API for Internationalization service.
// All implementations must embed UnimplementedInternationalizationServer
// for forward compatibility
type InternationalizationServer interface {
	// Method Version
	Version(context.Context, *emptypb.Empty) (*VersionResponse, error)
	mustEmbedUnimplementedInternationalizationServer()
}

// UnimplementedInternationalizationServer must be embedded to have forward compatible implementations.
type UnimplementedInternationalizationServer struct {
}

func (UnimplementedInternationalizationServer) Version(context.Context, *emptypb.Empty) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedInternationalizationServer) mustEmbedUnimplementedInternationalizationServer() {}

// UnsafeInternationalizationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternationalizationServer will
// result in compilation errors.
type UnsafeInternationalizationServer interface {
	mustEmbedUnimplementedInternationalizationServer()
}

func RegisterInternationalizationServer(s grpc.ServiceRegistrar, srv InternationalizationServer) {
	s.RegisterService(&Internationalization_ServiceDesc, srv)
}

func _Internationalization_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternationalizationServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internationalization.v1.Internationalization/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternationalizationServer).Version(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Internationalization_ServiceDesc is the grpc.ServiceDesc for Internationalization service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Internationalization_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "internationalization.v1.Internationalization",
	HandlerType: (*InternationalizationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _Internationalization_Version_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "npool/internationalization.proto",
}
