// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package npool

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InternalizationClient is the client API for Internalization service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalizationClient interface {
	// Method Version
	Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type internalizationClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalizationClient(cc grpc.ClientConnInterface) InternalizationClient {
	return &internalizationClient{cc}
}

func (c *internalizationClient) Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/internalization.v1.Internalization/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalizationServer is the server API for Internalization service.
// All implementations must embed UnimplementedInternalizationServer
// for forward compatibility
type InternalizationServer interface {
	// Method Version
	Version(context.Context, *emptypb.Empty) (*VersionResponse, error)
	mustEmbedUnimplementedInternalizationServer()
}

// UnimplementedInternalizationServer must be embedded to have forward compatible implementations.
type UnimplementedInternalizationServer struct {
}

func (UnimplementedInternalizationServer) Version(context.Context, *emptypb.Empty) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedInternalizationServer) mustEmbedUnimplementedInternalizationServer() {}

// UnsafeInternalizationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalizationServer will
// result in compilation errors.
type UnsafeInternalizationServer interface {
	mustEmbedUnimplementedInternalizationServer()
}

func RegisterInternalizationServer(s grpc.ServiceRegistrar, srv InternalizationServer) {
	s.RegisterService(&Internalization_ServiceDesc, srv)
}

func _Internalization_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalizationServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internalization.v1.Internalization/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalizationServer).Version(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Internalization_ServiceDesc is the grpc.ServiceDesc for Internalization service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Internalization_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "internalization.v1.Internalization",
	HandlerType: (*InternalizationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _Internalization_Version_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "npool/internalization.proto",
}
