// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AppLang is the predicate function for applang builders.
type AppLang func(*sql.Selector)

// Lang is the predicate function for lang builders.
type Lang func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)
